version: '3'

services:

  rhies-client-registry-server:
    image: registry.gitlab.com/rbc5/shared-health-registry:latest
    container_name: rhies-shr-server
    ports:
      - "8079:8080"
    restart: always
    volumes:
      - ./disc/rhies-shr-server/:/usr/local/tomcat/RhiesShr/
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
